Restore usual docker

diff --git a/.github/workflows/test-packaging.yml b/.github/workflows/test-packaging.yml
--- a/.github/workflows/test-packaging.yml
+++ b/.github/workflows/test-packaging.yml
@@ -42,12 +42,30 @@ jobs:
 
     steps:
 
-    - name: Start colima
-      timeout-minutes: 5
-      if: contains(matrix.os, 'macos')
+    # Docker needs to be installed manually on macOS.
+    # From https://github.com/docker/for-mac/issues/2359#issuecomment-943131345
+    # FIXME: lock Docker version to 4.10.0 as newer versions fail to initialize
+    #
+    # NOTE(lucas): I tried using colima just like in .github/workflows/fleetctl-preview.yml
+    # and .github/workflows/fleetctl-preview-latest.yml but `fleetctl package --type=msi`
+    # fails on the Heat stage.
+    - name: Install Docker
+      timeout-minutes: 20
+      if: matrix.os == 'macos-latest'
       run: |
-        brew install docker docker-compose
-        colima start
+        curl -L https://raw.githubusercontent.com/Homebrew/homebrew-cask/c65030146a5cf2070c2499b6c68e2c3495c99731/Casks/docker.rb > docker.rb
+        brew install --cask docker.rb
+        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+        open -a /Applications/Docker.app --args --unattended --accept-license
+        echo "Waiting for Docker to start up..."
+        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do
+          sleep 1;
+        done
+        echo "Docker is ready."
+
+    - name: Pull fleetdm/wix
+      # Run in background while other steps complete to speed up the workflow
+      run: docker pull fleetdm/wix:latest &
 
     - name: Install Go
       uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v2
