set default shell in workflows

diff --git a/.github/workflows/test-go.yaml b/.github/workflows/test-go.yaml
--- a/.github/workflows/test-go.yaml
+++ b/.github/workflows/test-go.yaml
@@ -19,6 +19,11 @@ on:
   schedule:
     - cron: '0 4 * * *'
 
+defaults:
+  run:
+    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
+    shell: bash
+
 permissions:
   contents: read
 
@@ -65,8 +70,6 @@ jobs:
         echo "GO_TEST_TIMEOUT=1h" >> $GITHUB_ENV
 
     - name: Run Go Tests
-      # bash shell sets -eo pipefail so that the pipe to tee will exit with an error if test-go fails
-      shell: bash
       run: |
         GO_TEST_EXTRA_FLAGS="-v -race=$RACE_ENABLED -timeout=$GO_TEST_TIMEOUT" \
           TEST_LOCK_FILE_PATH=$(pwd)/lock \
